# Generated by Django 5.1.15 on 2026-08-28 07:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_system_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationlog',
            name='operated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间'),
        ),
    ]
