# Generated by Django 6.1 on 2026-08-30 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_operationlog_operated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='分类名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='分类编码')),
                ('status', models.CharField(choices=[('1', '启用'), ('0', '停用')], default='1', max_length=16, verbose_name='状态')),
            ],
            options={
                'verbose_name': '接口分类',
                'verbose_name_plural': '接口分类',
                'db_table': 'sys_api_category',
                'ordering': ['sort_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ApiInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=128, verbose_name='接口名称')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], default='GET', max_length=10, verbose_name='请求方法')),
                ('path', models.CharField(max_length=500, verbose_name='接口路径')),
                ('version', models.CharField(default='v1', max_length=16, verbose_name='版本')),
                ('status', models.CharField(choices=[('1', '启用'), ('0', '停用')], default='1', max_length=16, verbose_name='状态')),
                ('need_auth', models.BooleanField(default=True, verbose_name='是否需要认证')),
                ('headers', models.JSONField(blank=True, default=list, verbose_name='默认请求头')),
                ('query_params', models.JSONField(blank=True, default=list, verbose_name='默认请求参数')),
                ('body', models.TextField(blank=True, default='', verbose_name='请求体示例')),
                ('response_example', models.TextField(blank=True, default='', verbose_name='响应示例')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apis', to='api.apicategory', verbose_name='所属分类')),
            ],
            options={
                'verbose_name': '接口信息',
                'verbose_name_plural': '接口信息',
                'db_table': 'sys_api_info',
                'ordering': ['sort_order', '-id'],
                'unique_together': {('method', 'path', 'version')},
            },
        ),
    ]
