# Generated by Django 6.1 on 2026-08-30 07:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_apicategory_apiinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='节点名称')),
                ('node_id', models.CharField(max_length=64, unique=True, verbose_name='节点唯一标识')),
                ('host', models.CharField(max_length=64, verbose_name='主机地址')),
                ('port', models.PositiveIntegerField(default=8000, verbose_name='端口')),
                ('is_local', models.BooleanField(default=False, verbose_name='是否本机节点')),
                ('status', models.CharField(choices=[('1', '启用'), ('0', '停用')], default='1', max_length=4, verbose_name='启用状态')),
                ('max_concurrency', models.PositiveIntegerField(default=4, verbose_name='最大并发数')),
                ('current_load', models.PositiveIntegerField(default=0, verbose_name='当前负载')),
                ('version', models.CharField(blank=True, default='', max_length=32, verbose_name='执行器版本')),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True, verbose_name='最后心跳时间')),
            ],
            options={
                'verbose_name': '执行节点',
                'verbose_name_plural': '执行节点',
                'ordering': ['sort_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='任务名称')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='任务描述')),
                ('job_type', models.CharField(choices=[('function', '内置函数'), ('http', 'HTTP请求')], default='function', max_length=16, verbose_name='任务类型')),
                ('handler', models.CharField(blank=True, default='', max_length=64, verbose_name='内置处理器')),
                ('http_method', models.CharField(blank=True, default='GET', max_length=8, verbose_name='HTTP方法')),
                ('http_url', models.CharField(blank=True, default='', max_length=500, verbose_name='HTTP地址')),
                ('http_body', models.TextField(blank=True, default='', verbose_name='HTTP请求体')),
                ('trigger_type', models.CharField(choices=[('cron', 'CRON表达式'), ('interval', '固定间隔'), ('date', '指定时间')], default='cron', max_length=16, verbose_name='触发方式')),
                ('cron_expr', models.CharField(blank=True, default='', help_text="5段式: 分 时 日 月 周, 如 '0 3 * * *' 每天3点", max_length=64, verbose_name='CRON表达式')),
                ('interval_seconds', models.PositiveIntegerField(default=60, verbose_name='间隔秒数')),
                ('run_date', models.DateTimeField(blank=True, null=True, verbose_name='指定执行时间')),
                ('priority', models.CharField(choices=[('1', '高'), ('2', '中'), ('3', '低')], default='2', max_length=4, verbose_name='优先级')),
                ('timeout_seconds', models.PositiveIntegerField(default=300, verbose_name='超时秒数')),
                ('status', models.CharField(choices=[('1', '启用'), ('0', '停用')], default='1', max_length=4, verbose_name='状态')),
                ('next_run_at', models.DateTimeField(blank=True, null=True, verbose_name='下次执行时间')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='上次执行时间')),
                ('last_status', models.CharField(blank=True, default='', max_length=16, verbose_name='上次执行状态')),
            ],
            options={
                'verbose_name': '定时任务',
                'verbose_name_plural': '定时任务',
                'ordering': ['sort_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('remark', models.CharField(blank=True, default='', max_length=255, verbose_name='备注')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('job_name', models.CharField(max_length=64, verbose_name='任务名称快照')),
                ('node_name', models.CharField(blank=True, default='', max_length=64, verbose_name='节点名称快照')),
                ('status', models.CharField(choices=[('running', '执行中'), ('success', '成功'), ('failed', '失败'), ('timeout', '超时')], default='running', max_length=16, verbose_name='执行状态')),
                ('trigger', models.CharField(blank=True, default='', max_length=16, verbose_name='触发方式快照')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('duration_ms', models.PositiveIntegerField(default=0, verbose_name='耗时(ms)')),
                ('output', models.TextField(blank=True, default='', verbose_name='执行输出')),
                ('error_msg', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='api.schedulernode', verbose_name='执行节点')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='api.taskjob', verbose_name='任务')),
            ],
            options={
                'verbose_name': '任务执行日志',
                'verbose_name_plural': '任务执行日志',
                'ordering': ['-started_at', '-id'],
            },
        ),
    ]
