# Generated by Django 6.1 on 2026-08-30 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_schedulernode_taskjob_taskexecutionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiinfo',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='apiinfo',
            unique_together=None,
        ),
        migrations.DeleteModel(
            name='ApiCategory',
        ),
        migrations.DeleteModel(
            name='ApiInfo',
        ),
    ]
