/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  home: () => import("@/views/home/index.vue"),
  monitor_cache: () => import("@/views/monitor_cache/index.vue"),
  monitor_file: () => import("@/views/monitor_file/index.vue"),
  monitor_server: () => import("@/views/monitor_server/index.vue"),
  system_config: () => import("@/views/system_config/index.vue"),
  system_dept: () => import("@/views/system_dept/index.vue"),
  system_dict: () => import("@/views/system_dict/index.vue"),
  system_log: () => import("@/views/system_log/index.vue"),
  system_menu: () => import("@/views/system_menu/index.vue"),
  system_post: () => import("@/views/system_post/index.vue"),
  system_role: () => import("@/views/system_role/index.vue"),
  system_user: () => import("@/views/system_user/index.vue"),
};
