/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'apis',
    path: '/apis',
    component: 'layout.base',
    meta: {
      title: 'apis',
      i18nKey: 'route.apis'
    },
    children: [
      {
        name: 'apis_docs',
        path: '/apis/docs',
        component: 'view.apis_docs',
        meta: {
          title: 'apis_docs',
          i18nKey: 'route.apis_docs'
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'monitor',
    path: '/monitor',
    component: 'layout.base',
    meta: {
      title: 'monitor',
      i18nKey: 'route.monitor'
    },
    children: [
      {
        name: 'monitor_cache',
        path: '/monitor/cache',
        component: 'view.monitor_cache',
        meta: {
          title: 'monitor_cache',
          i18nKey: 'route.monitor_cache'
        }
      },
      {
        name: 'monitor_file',
        path: '/monitor/file',
        component: 'view.monitor_file',
        meta: {
          title: 'monitor_file',
          i18nKey: 'route.monitor_file'
        }
      },
      {
        name: 'monitor_server',
        path: '/monitor/server',
        component: 'view.monitor_server',
        meta: {
          title: 'monitor_server',
          i18nKey: 'route.monitor_server'
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: 'system',
      i18nKey: 'route.system'
    },
    children: [
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: 'system_config',
          i18nKey: 'route.system_config'
        }
      },
      {
        name: 'system_dept',
        path: '/system/dept',
        component: 'view.system_dept',
        meta: {
          title: 'system_dept',
          i18nKey: 'route.system_dept'
        }
      },
      {
        name: 'system_dict',
        path: '/system/dict',
        component: 'view.system_dict',
        meta: {
          title: 'system_dict',
          i18nKey: 'route.system_dict'
        }
      },
      {
        name: 'system_log',
        path: '/system/log',
        component: 'view.system_log',
        meta: {
          title: 'system_log',
          i18nKey: 'route.system_log'
        }
      },
      {
        name: 'system_menu',
        path: '/system/menu',
        component: 'view.system_menu',
        meta: {
          title: 'system_menu',
          i18nKey: 'route.system_menu'
        }
      },
      {
        name: 'system_post',
        path: '/system/post',
        component: 'view.system_post',
        meta: {
          title: 'system_post',
          i18nKey: 'route.system_post'
        }
      },
      {
        name: 'system_role',
        path: '/system/role',
        component: 'view.system_role',
        meta: {
          title: 'system_role',
          i18nKey: 'route.system_role'
        }
      },
      {
        name: 'system_user',
        path: '/system/user',
        component: 'view.system_user',
        meta: {
          title: 'system_user',
          i18nKey: 'route.system_user'
        }
      }
    ]
  },
  {
    name: 'task',
    path: '/task',
    component: 'layout.base',
    meta: {
      title: 'task',
      i18nKey: 'route.task',
      icon: 'mdi:clock-time-eight-outline',
      order: 30
    },
    children: [
      {
        name: 'task_job',
        path: '/task/job',
        component: 'view.task_job',
        meta: {
          title: 'task_job',
          i18nKey: 'route.task_job',
          icon: 'mdi:calendar-clock',
          order: 1
        }
      },
      {
        name: 'task_node',
        path: '/task/node',
        component: 'view.task_node',
        meta: {
          title: 'task_node',
          i18nKey: 'route.task_node',
          icon: 'mdi:server-network',
          order: 3
        }
      },
      {
        name: 'task_scheduler',
        path: '/task/scheduler',
        component: 'view.task_scheduler',
        meta: {
          title: 'task_scheduler',
          i18nKey: 'route.task_scheduler',
          icon: 'mdi:monitor-eye',
          order: 2
        }
      }
    ]
  }
];
